user:
  local.static.file:
    endpoint: /files/
    path: /opt/files/

spring:
  profiles:
    active: '@activatedProperties@'

---

spring:
  profiles: dev-docker
  data.mongodb:
    database: test
    uri: mongodb://circularshiftdb:30002/test
    repositories.enabled: true
    
server:
  port: 8081

---

spring:
  profiles: dev-kubernetes
  data.mongodb:
    database: test
    uri: mongodb://192.168.99.113:30873/test
    repositories.enabled: true

server:
  port: 8081