apiVersion: v1
kind: Service
metadata:
  name: chairwise-sorting-service
  labels:
   run: chairwise-sorting-service
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 8000
    protocol: TCP
  selector:
    run: chairwise-sorting-service