version: "3"
services:
  circularshiftdb:
    image: mongo:latest
    command: mongod --port 30002
    expose:
      - 30002
    ports:
      - 30002:30002
    volumes:
      - ./circularshiftdb/db:/data/db
      - ./circularshiftdb/configdb:/data/configdb
    restart: always
    networks:
      - circularshiftnetwork
  circularshiftapi:
    build: .
    expose: 
      - 8081
    ports:
      - 8081:8081
    restart: always
    networks:
      - chairwise-input-service_inputnetwork
      - circularshiftnetwork
networks:
  circularshiftnetwork:
    driver: bridge
  chairwise-input-service_inputnetwork:
    external: true